### PR TITLE
NewIDE Patch

### PR DESCRIPTION
**Pull request by ArunJayan**
using this  we will start creating Latest IDE patch

### CODE REVIEW

**Comment by georgesk** [comment]
Tanks! I shall rebuild the debian package shortly.

**Comment by ArunJayan** [comment]
Sir
   Wait ... I need some time to fix some bugs in new UI ..  I will upload
new code very soon this repository

Sir , I need a small help to create a debian package of my qt+opencv
project

**Comment by georgesk** [comment]
Dear Arun,

Arun Jayan a écrit :
> Sir , I need a small help to create a debian package of my qt+opencv
> project

What kind of help would you ask for?

Best regards,			Georges.

**Comment by ArunJayan** [comment]
Hey expeyes/expeyes-prog,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Arun

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=yCMD0xty&invitationId=6191941519809789952&trk=eml-invite_guest-invite_guest-203-india_a&trkEmail=eml-invite_guest-invite_guest-203-india_a-null-0%7Eiu6vdmob%7Ejo



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iu6vdmob-jo&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHdARqgcMz8qwAAAVe4zTw3reNQjqQB6d7ApoI2TliX2C0u5m8GsHmZxZ5eUgnahVDSxyXnih7BiEeXK_oKmfAVvmrakkg2Es39T6gL5m324d89i44fZcHCvlwQ2fOZ_fOh-YGm4gfSFCZ60p2KeDI1KnFzFF6P2yJhoulLcZEc1V4mnsOl0mh9l79DgmRpiNll&eid=0-iu6vdmob-jo


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iu6vdmob-jo&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ArunJayan** [comment]
Arun Jayan would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=yCMD0xty&invitationId=6191941519809789952&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Ewrlbo2%7Eiugnyqfw%7Eah

View Arun Jayan&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=yCMD0xty&invitationId=6191941519809789952&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Ewrlbo2%7Eiugnyqfw%7Eah





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wrlbo2-iugnyqfw-ah&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-wrlbo2-iugnyqfw-ah&loid=AQFIS9Fe2RCWjAAAAVfcsP6--rPOjJmX7GTcuzw8Q8IkYm2LLte17FMkmhFyUoAFt-nVwnr-i_ZTnnOFf9K7LRLqdgUxcVI6NcH365iNxic7hxrcYMyDUCSua7j8WIioV_fbiuxPthTsOnmGWuC1H-EpGH3xiXA9eS3sysaNcnN-2gYeBhgS1S_09QMqoxAdK8I3

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-wrlbo2-iugnyqfw-ah&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ArunJayan** [comment]
Hi ,

Arun Jayan would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=yCMD0xty&invitationId=6191941519809789952&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Ewrlbo2%7Eiuqf1xri%7Evh

View Arun Jayan&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=yCMD0xty&invitationId=6191941519809789952&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Ewrlbo2%7Eiuqf1xri%7Evh





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wrlbo2-iuqf1xri-vh&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-wrlbo2-iuqf1xri-vh&loid=AQHEb-rZjpu4AAAAAVf_2b6AdTBTn58dUAND0O-cJ6abKbUp_Ca1-ZfYdV0cwC1CPKi3XZed44gwzBFa5s1YWFe0uNYwBM8j-zwNtZY-bRE5_qRDPwOt2jT2Oy_K6KgGgo5HDcE_SGULwwuFRsgVoqe630iezBOmQ0GcxJu1CrnNnVLnJN_oPwJOcmddretIZnx1

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-wrlbo2-iuqf1xri-vh&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
