### PR TITLE
Added GPL V3 Licence information to files

### PR DESCRIPTION
**Pull request by manoj-s-nair**

### CODE REVIEW

**Comment by georgesk** [comment]
Hi,

many thanks for your contribution. I shall increment he version number, and release a new debian package

**Comment by manoj-s-nair** [comment]
You are welcome. :+1:

**Comment by georgesk** [comment]
Hi, I began the packaging work for Debian. However there will be issues (maybe with licenses).

Some files are not in source format, even if we can parse them into some pretty format.
For example, it is the case of the file bootstrap.min.css.

When I prettify this file, it becomes readable (but thousands of lines long).

I suppose that you got this file from some place and never modified it. As sources are cited in comments of this file, can you try to replace the file bootstrap.min.css by files https://github.com/necolas/normalize.css/blob/master/normalize.css, https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css?

I see that part of the compressed file comes also from https://github.com/twbs/bootstrap, and it is made thanks to some magics which relies on a file which is not human-readable completely: bootstrap.min.css.map

-----------------------
I suppose that we do not need all of the thousands lines for expeyes-web. Can you identify a subset of those lines which would be enough for expeyes?

According to DFSG, Debian Free Software Guidelines, we must be able to provide a human-readable source to whoever want to understand our package. Hence the file bootstrap.min.css cannot be distributed if we do not provide a source for it, and a recipe to recompile it in minified format.

**Comment by georgesk** [comment]
By the way, can we exchange by ordinary e-mail? mine is georges.khaznadar@free.fr

**Pull request merged**
